// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5g-_wiDms8Q3P0hq9W42YKnUyGJqa8Ts',
    appId: '1:1001072464576:web:a580cfaa76459713391325',
    messagingSenderId: '1001072464576',
    projectId: 'daleel-naw3ya',
    authDomain: 'daleel-naw3ya.firebaseapp.com',
    storageBucket: 'daleel-naw3ya.firebasestorage.app',
    measurementId: 'G-HZRJ3S1JJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyw_PZfZMGfE0Vc3qXFIYAsnO5kN3E944',
    appId: '1:1001072464576:android:8c00559397bcb57a391325',
    messagingSenderId: '1001072464576',
    projectId: 'daleel-naw3ya',
    storageBucket: 'daleel-naw3ya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMb-ze5B2vZyAJGk0S_hRN-QsijMM7i8',
    appId: '1:1001072464576:ios:e949d721e83974fd391325',
    messagingSenderId: '1001072464576',
    projectId: 'daleel-naw3ya',
    storageBucket: 'daleel-naw3ya.firebasestorage.app',
    iosBundleId: 'com.example.daleelNaw3ya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMb-ze5B2vZyAJGk0S_hRN-QsijMM7i8',
    appId: '1:1001072464576:ios:e949d721e83974fd391325',
    messagingSenderId: '1001072464576',
    projectId: 'daleel-naw3ya',
    storageBucket: 'daleel-naw3ya.firebasestorage.app',
    iosBundleId: 'com.example.daleelNaw3ya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5g-_wiDms8Q3P0hq9W42YKnUyGJqa8Ts',
    appId: '1:1001072464576:web:9d3248ee9713d873391325',
    messagingSenderId: '1001072464576',
    projectId: 'daleel-naw3ya',
    authDomain: 'daleel-naw3ya.firebaseapp.com',
    storageBucket: 'daleel-naw3ya.firebasestorage.app',
    measurementId: 'G-GLE70N2MX8',
  );
}
